# Generated by Django 5.1.7 on 2025-03-27 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("email", models.EmailField(max_length=100, null=True, unique=True, verbose_name="이메일")),
                ("nickname", models.CharField(max_length=30, null=True, verbose_name="닉네임")),
                ("is_active", models.BooleanField(default=False, verbose_name="활성 상태")),
                ("is_staff", models.BooleanField(default=False, verbose_name="스태프 여부")),
                ("gender", models.CharField(max_length=10, null=True, verbose_name="성별")),
                ("age", models.IntegerField(null=True, verbose_name="나이")),
                ("social_provider", models.CharField(max_length=20, null=True, verbose_name="소셜 제공자")),
                ("social_id", models.CharField(max_length=50, null=True, verbose_name="소셜 아이디")),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        default="profile_images/default_profile_image.jpg",
                        null=True,
                        upload_to="profile_images/",
                        verbose_name="프로필 이미지",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저 목록",
                "db_table": "user",
            },
        ),
    ]
