# Generated by Django 5.1.7 on 2025-03-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userimage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
