# Generated by Django 5.1.7 on 2025-03-27 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("artist_group", models.CharField(blank=True, max_length=30, null=True, verbose_name="아티스트 그룹")),
                ("artist_agency", models.CharField(blank=True, max_length=30, null=True, verbose_name="소속사")),
                ("group_insta", models.CharField(blank=True, max_length=100, null=True, verbose_name="인스타그램")),
                (
                    "group_fandom",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="아티스트그룹팬덤"),
                ),
                ("debut_date", models.DateField(blank=True, null=True, verbose_name="데뷔 날짜")),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="artist_groups/", verbose_name="그룹 이미지"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "아티스트 그룹",
                "verbose_name_plural": "아티스트 그룹 목록",
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("artist_name", models.CharField(default="Unknown", max_length=30, verbose_name="이름")),
                ("artist_agency", models.CharField(blank=True, max_length=30, null=True, verbose_name="소속사")),
                ("artist_insta", models.CharField(blank=True, max_length=100, null=True, verbose_name="인스타그램")),
                ("artist_fandom", models.CharField(blank=True, max_length=10, null=True, verbose_name="아티스트팬덤")),
                ("debut_date", models.DateField(blank=True, null=True, verbose_name="데뷔 날짜")),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="artists/", verbose_name="아티스트 이미지"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_artists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "artist_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="artists.artistgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "아티스트",
                "verbose_name_plural": "아티스트 목록",
            },
        ),
    ]
