# Generated by Django 5.1.7 on 2025-03-27 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 상태")),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                ("description", models.TextField(blank=True, null=True, verbose_name="설명")),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="시작 날짜")),
                ("end_date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="종료 날짜")),
                ("location", models.CharField(blank=True, max_length=100, null=True, verbose_name="장소")),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="위도"),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="경도"),
                ),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="schedule/", verbose_name="일정 이미지"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="artists.artist"
                    ),
                ),
                (
                    "artist_group",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="artists.artistgroup"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "일정",
                "verbose_name_plural": "일정 목록",
            },
        ),
    ]
